Series: scikit
Global:
  save_model_dir: /home/eugene/workspace/ryuocr/py/checkpoint/
  save_result_dir: /home/eugene/workspace/ryuocr/py/output/


  
Optimizer:
  learning_rate: 0.0001
  name: Adam
  beta1: 0.9
  beta2: 0.999

  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  network:
    name: MLP
    hidden_layer: 512 
  
Train:
  epoch: 400
  print_iter_step: 20

  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 2000]
  dataset:
    ttfpath :
      - "/home/eugene/workspace/dataset/font/font/7/AozoraMinchoRegular.ttf"
      - "/home/eugene/workspace/dataset/font/font/7/GenShinGothic-Regular.ttf"
      - "/home/eugene/workspace/dataset/font/font/7/logotypejp_corpmin.ttf"
      - "/home/eugene/workspace/dataset/font/font/7/mgenplus-1c-regular.ttf"
      - "/home/eugene/workspace/dataset/font/font/7/mplus-1c-regular.ttf"
      - "/home/eugene/workspace/dataset/font/font/7/VL-Gothic-Regular.ttf"
      - "/home/eugene/workspace/dataset/font/font/7/yasashisa_gothic.ttf"
    dict : "/home/eugene/workspace/dataset/dict/japanese_3107jp.txt"
    fontsize: 64
    sscdsize: 20
    transform:

Test:
  dataset:
    name: JPSC1400
    dir: /home/eugene/workspace/dataset/scenetext/JPSC1400-20201218/rec_gt_test.txt