---
Global:
  save_model_dir: ./checkpoint/
  save_result_dir: ./output/

  pretrained_model: 2021-07-16-18-10-39

Train:
  series: torch
  torch:
    gpu: True
    architecture:
      # name: vgg11_offical
      # name: resnet34_offical
      # name: mobilenet_offical
      name: mynonepoolnet
      # name: myvgg
      parameter:
        kernel_size: 6
        stride: 2
        numlayer_perds: 1
        classifier_arch: "LDLD"
        # classifier_arch: "DLD"

        input_size: 64
        input_channel: 3
        feature_size: 4
        feature_channel: 512
        first33: False
    loss:
      name: crossentropy
      # name: L2
      # factor: 0.00001
    process:
      - loop: 1
        sscd:
          type: sample
          num: 500000
        para:
          epoch: 20
          batchsize: 128
          shuffle: True
          print: True
          valid: True
          iter_step: 100
        optimizer:
          name: adam
          lr: 0.0001
          betas: [0.9, 0.999]
      # - loop: 50
      #   sscd:
      #     type: sample
      #     # num: 50000
      #     num: 20000
      #     # type: bunch
      #     # num: 1
      #   para:
      #     epoch: 1
      #     batchsize: 128
      #     shuffle: True
      #     print: True
      #     valid: True
      #     iter_step: 100
      #   optimizer:
      #     name: adam
      #     lr: 0.001
      #     # betas: [0.9, 0.999]
      #     scheduler:
      #       name: lineral
      #       # gamma: 0.9
      #       endepoch: 50

  dataset:
    type: sscd
    profile:
      ttfpaths:
        - /home/eugene/workspace/dataset/font/7/AozoraMinchoRegular.ttf
        - /home/eugene/workspace/dataset/font/7/GenShinGothic-Regular.ttf
        - /home/eugene/workspace/dataset/font/7/logotypejp_corpmin.ttf
        - /home/eugene/workspace/dataset/font/7/mgenplus-1c-regular.ttf
        - /home/eugene/workspace/dataset/font/7/mplus-1c-regular.ttf
        - /home/eugene/workspace/dataset/font/7/VL-Gothic-Regular.ttf
        - /home/eugene/workspace/dataset/font/7/yasashisa_gothic.ttf
      # ttfpaths:
      #   - /home/eugene/workspace/dataset/font/7/AozoraMinchoRegular.ttf
      #   - /home/eugene/workspace/dataset/font/7/GenShinGothic-Regular.ttf
      #   - /home/eugene/workspace/dataset/font/7/logotypejp_corpmin.ttf
      #   - /home/eugene/workspace/dataset/font/7/mgenplus-1c-regular.ttf
      #   - /home/eugene/workspace/dataset/font/7/mplus-1c-regular.ttf
      #   - /home/eugene/workspace/dataset/font/7/VL-Gothic-Regular.ttf
      #   - /home/eugene/workspace/dataset/font/7/yasashisa_gothic.ttf
      #   - /home/eugene/workspace/dataset/font/ryujpfontset/1_gomarice_mukasi_mukasi.ttf
      #   - /home/eugene/workspace/dataset/font/ryujpfontset/2_851tegaki_zatsu_normal_0883.ttf
      dictpara:
        dictpath: /home/eugene/workspace/dataset/dict/japanese_3107jp.txt
        revise: False
      fontsize: 64
      padding: 2
      transform:
        - name: morph
          p: 0.7
          patterns:
            - dilation4
            - dilation8
            - erosion4l
        # - name: affine
        #   rotation: 30
        #   shear: [15, 15]
        #   autoscale: True
        #   p: 1
        - name: perspective
          scale: [-0.1, 0.2]
          p: 1
        - name: color
          gap: 50
        # # -
        # #   name: gaussian_noise
        # #   mean: [0,0]
        # #   var: [0.01,0.01]
        - name: gaussian_filter
          sigma: [0, 10]
        - name: random_filter
          scale: [-1, 1]
        - name: gaussian_filter
          sigma: [0, 10]
        - name: random_filter
          scale: [-1, 1]
        - name: gaussian_filter
          sigma: [0, 10]
        - name: random_filter
          scale: [-1, 1]
        - name: gaussian_filter
          sigma: [0, 10]
        - name: gaussian_noise
          mean: [0, 0]
          var: [0.01, 0.01]

Test:
  dataset:
    type: real
    profile:
      name: JPSC1400
      dir: /home/eugene/workspace/dataset/scenetext/JPSC1400-20201218/rec_gt_test.txt
      revise: False
