---
Global:
  save_result_dir: ./output/
  pretrained_model: 2021-12-21-15-27-26torch

Train:
  series: torch
  torch:
    gpu: True
    architecture:
      # name: vgg11_offical
      # name: resnet34_offical
      # name: mobilenet_offical
      name: mynonepoolnet
      # name: myvgg
      parameter:
        # Only for mynonepoolnet
        stride: 2
        kernel_size: 6


        # classifier_arch: "LDLD"
        classifier_arch: "DLD"

        numlayer_perds: 1

        input_size: 64
        input_channel: 3

        feature_channel: 512
        feature_size: 4
        channel_time: 2

        first33: False
    loss:
      name: crossentropy
      # name: L2
      # factor: 0.00001
    process:
      - loop: 1
        sscd:
          type: sample
          num: 500000
        para:
          # epoch: ['loss',0.5]
          epoch: 40
          
          batchsize: 128
          shuffle: True
          print: True
          valid: True
          iter_step: 100
        optimizer:
          name: adam
          lr: 0.0001
          betas: [0.9, 0.999]
      # - loop: 50
      #   sscd:
      #     type: sample
      #     # num: 50000
      #     num: 20000
      #     # type: bunch
      #     # num: 1
      #   para:
      #     epoch: 1
      #     batchsize: 128
      #     shuffle: True
      #     print: True
      #     valid: True
      #     iter_step: 100
      #   optimizer:
      #     name: adam
      #     lr: 0.001
      #     # betas: [0.9, 0.999]
      #     scheduler:
      #       name: lineral
      #       # gamma: 0.9
      #       endepoch: 50

  dataset:
    type: sscd
    profile:
      ttfpaths:
        - /home/eugene/workspace/dataset/font/japanese7/AozoraMinchoRegular.ttf
        - /home/eugene/workspace/dataset/font/japanese7/GenShinGothic-Regular.ttf
        - /home/eugene/workspace/dataset/font/japanese7/logotypejp_corpmin.ttf
        - /home/eugene/workspace/dataset/font/japanese7/mgenplus-1c-regular.ttf
        - /home/eugene/workspace/dataset/font/japanese7/mplus-1c-regular.ttf
        - /home/eugene/workspace/dataset/font/japanese7/VL-Gothic-Regular.ttf
        - /home/eugene/workspace/dataset/font/japanese7/yasashisa_gothic.ttf
      # ttfpaths:
      #   - /home/eugene/workspace/dataset/font/japanese7/AozoraMinchoRegular.ttf
      #   - /home/eugene/workspace/dataset/font/japanese7/GenShinGothic-Regular.ttf
      #   - /home/eugene/workspace/dataset/font/japanese7/logotypejp_corpmin.ttf
      #   - /home/eugene/workspace/dataset/font/japanese7/mgenplus-1c-regular.ttf
      #   - /home/eugene/workspace/dataset/font/japanese7/mplus-1c-regular.ttf
      #   - /home/eugene/workspace/dataset/font/japanese7/VL-Gothic-Regular.ttf
      #   - /home/eugene/workspace/dataset/font/japanese7/yasashisa_gothic.ttf
      #   - /home/eugene/workspace/dataset/font/japanese_collectByRyu/1_gomarice_mukasi_mukasi.ttf
      #   - /home/eugene/workspace/dataset/font/japanese_collectByRyu/2_851tegaki_zatsu_normal_0883.ttf
      dictpara:
        dictpath: /home/eugene/workspace/dataset/dict/japanese_3107jp.txt
        revise: False
      fontsize: 64
      padding: 2
      transform:

        # Affine Transformations
        # - name: affine
        #   rotation: 0
        #   shear: [-15, 15]
        #   autoscale: True
        #   p: 1
      
        # Perspective Transformation
        - name: perspective
          scale: [-0.1, 0.2]
          p: 1
        # - name: perspective_direct
        #   scale: [-5,5]
        #   p: 1

        # Morphology Transformation
        # - name: morph_ski
        #   p: 1
        #   patterns:
        #     - dilation8
        #     - erosion8
        #     - none
        - name: morph
          p: 0.7
          patterns:
            - dilation4
            - dilation8
            - pushU
            - pushD


        # - name: morph
        #   p: 1
        #   patterns:
        #     - dilation4
        #     - dilation8
        #     - pushU
        #     - pushD
        #     - none
        #     - notrans

        # Perspective Transformation
        # - name: perspective
        #   scale: [-0.1, 0.2]
        #   p: 1
        # - name: perspective_direct
          # scale: [-5,5]
          # p: 1
        
        
        # Color Generation 
        - name: color
          gap: 50
        # - name: color_lib
        
        - name: gaussian_filter
          sigma: [0, 10]


        - name: random_filter
          scale: [-1, 1]
        - name: gaussian_filter
          sigma: [0, 10]
        # - name: random_filter
        #   scale: [-1, 1]
        # - name: gaussian_filter
        #   sigma: [0, 10]
        - name: random_filter
          scale: [-1, 1]
        - name: gaussian_filter
          sigma: [0, 10]
        - name: random_filter
          scale: [-1, 1]
        - name: gaussian_filter
          sigma: [0, 10]
        # - name: random_filter
        #   scale: [-1, 1]
        # - name: gaussian_filter
        #   sigma: [0, 10]
        - name: gaussian_noise
          mean: [0, 0]
          var: [0.01, 0.01]


Test:
  dataset:
    type: real
    profile:
      name: JPSC1400
      dir: /home/eugene/workspace/dataset/scenetext/JPSC1400-20201218/rec_gt_test.txt
      dictpath: /home/eugene/workspace/dataset/dict/japanese_3107jp.txt
  revise: False
