Global:
  use_gpu: True
  epoch: 400
  print_iter_step: 20
  save_model_dir: /home/eugene/workspace/ryuocr/py/trained/
  save_result_dir: /home/eugene/workspace/ryuocr/py/output/

  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 2000]

Optimizer:
  learning_rate: 0.0001
  name: Adam
  beta1: 0.9
  beta2: 0.999

  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  network:
    name: MLP
    hidden_layer: 512 
  
Train:
  dataset:
    # name: "20_20210406184753"
    # data_dir: /home/eugene/workspace/ryuocr/py/tensorsscd/
    # label_dir: /home/eugene/workspace/ryuocr/py/tensorsscd/
    ttfpath :
      - "/home/eugene/workspace/resource/font/7/AozoraMinchoRegular.ttf"
      - "/home/eugene/workspace/resource/font/7/GenShinGothic-Regular.ttf"
      - "/home/eugene/workspace/resource/font/7/logotypejp_corpmin.ttf"
      - "/home/eugene/workspace/resource/font/7/mgenplus-1c-regular.ttf"
      - "/home/eugene/workspace/resource/font/7/mplus-1c-regular.ttf"
      - "/home/eugene/workspace/resource/font/7/VL-Gothic-Regular.ttf"
      - "/home/eugene/workspace/resource/font/7/yasashisa_gothic.ttf"
    dict : "/home/eugene/workspace/dataset/font/dict3107jp.txt"
    fontsize: 64
    sscdsize: 20
    transform:


  loader:
    shuffle: True
    batch_size: 256

Test:
  dataset:
    name: JPSC1400
    dir: /home/eugene/workspace/dataset/scenetext/JPSC1400-20201218/rec_gt_test.txt
  loader:
    shuffle: False
    batch_size: 256
